AWSTemplateFormatVersion: "2010-09-09"
Resources:
  HeroesSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: /HeroesSecrets
      SecretString: >
        {
          "github.clientId": "2f34ea46fa982a2a0320",
          "github.clientSecret": "3ba2d781d546937ac7c61a35f7d6f1489c81fedc",
          "google.clientId": "1091971459089-a850f6i1pj45odr0up9ag13h4v7ha03g.apps.googleusercontent.com",
          "google.clientSecret": "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"
        }

  HeroesDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "name"
          AttributeType: "S"
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "hero"
      GlobalSecondaryIndexes:
        -
          IndexName: "myGSI"
          KeySchema:
            -
              AttributeName: "name"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
