spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 2f34ea46fa982a2a0320
            clientSecret: 3ba2d781d546937ac7c61a35f7d6f1489c81fedc
          google:
            client-id: 1091971459089-a850f6i1pj45odr0up9ag13h4v7ha03g.apps.googleusercontent.com
            client-secret: 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