spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${github.clientId}
            clientSecret: ${github.clientSecret}
          google:
            client-id: ${google.clientId}
            client-secret: ${google.clientSecret}
  config:
    import: 'optional:aws-secretsmanager:/HeroesSecrets'

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
