spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 7cd0d12608c0fea9d820
            clientSecret: 50d7dda611fd8cf1121abd8381f6e56a4a303fa1
          google:
            client-id: 1091971459089-a850f6i1pj45odr0up9ag13h4v7ha03g.apps.googleusercontent.com
            client-secret: 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

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
